{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_pytest/demo3.py:10: AssertionError"}, "description": "this test fails", "start": 1609854401763, "stop": 1609854401764, "uuid": "01a1cb5e-c70d-414a-bc0b-3a64c4ea0ab8", "historyId": "b5ffc0c82fc1d3a22285f36a4b2028fa", "testCaseId": "23d408115d368f9a14ab1a2a54eaeaad", "fullName": "test_pytest.demo3#test_failure", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "demo3"}, {"name": "host", "value": "AmydeAir"}, {"name": "thread", "value": "85585-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.demo3"}]}